### ISSUE TITLE
ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by amitabul** [hengruo/ZZXproj#1]
Thank you for sharing good code.

I ran `python main.py`
But an error has occurred.

```
$ python main.py
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import models
  File "/Users/tyler.ryu/PycharmProjects/RNet-pytorch/models.py", line 5, in <module>
    import utils
ModuleNotFoundError: No module named 'utils'
```

**Comment by wise-east** [comment]
I have the same problem. I hope there can be some update on this!

**Comment by francidellungo** [comment]
Still same problem!
